<?php

namespace KL\ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersWithGroups()
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->leftJoin('u.groupes', 'g')
            ->select('u.id')
            ->addSelect('u.prenom')
            ->addSelect('u.nom')
            ->addSelect('u.email')
            ->addSelect('u.dateCreation')
            ->addSelect('u.actif')
            ->addSelect('g.nomGroupe');

        return $qb->getQuery()
            ->getResult();
    }
}