<?php

namespace KL\ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use KL\ApiBundle\Entity\Groupe;


class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserWithGroups(array $groupe_list)
    {

    }

    public function getUsersWithGroups()
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->leftJoin('u.groupes', 'g')
            ->addSelect('g')
            ->select('u.id')
            ->addSelect('u.prenom')
            ->addSelect('u.nom')
            ->addSelect('u.email')
            ->addSelect('u.dateCreation')
            ->addSelect('u.actif')
            ->addSelect('g.nomGroupe');
            //->where('u.id = g.id');

        return $qb->getQuery()
            ->getResult();
    }

    public function findUserWithGroups(Groupe $groupe){
        $qb = $this->createQueryBuilder('u');

        $qb->where('u.groupes = :groupe')
            ->setParameter('groupe', $groupe);

        return $qb
            ->getQuery()
            ->getResult();
    }
}